#server:
#  servlet:
#    context-path: "/"
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/school
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true