create table subject
(
	id int2 generated by default as identity primary key,
	name varchar(50) not null,
	
	constraint uq__subject__name unique (name)
);

create table teacher
(
	id int4 generated always as identity primary key,
	first_name varchar(30) not null,
	last_name varchar(30) not null
);

create table teacher_subject
(
	id int4 generated always as identity primary key,
	teacher_id int4 not null,
	subject_id int4 not null,
	
	constraint fk__teacher_subject__teacher__id foreign key (teacher_id) references teacher (id),
	constraint fk__teacher_subject__subject__id foreign key (subject_id) references subject (id),
	constraint uq__teacher_subject__teacher_id_subject_id unique (teacher_id, subject_id)
);

create table student
(
	id int4 generated always as identity primary key,
	first_name varchar(30) not null,
	last_name varchar(30) not null
);

create table assessment 
(
	id int4 generated always as identity primary key,
	student_id int4 not null,
	teacher_id int4 not null,
	subject_id int4 not null,
	assessment int2 not null,
	created timestamp with time zone not null,
	
	constraint fk__assessment__student__id foreign key (student_id) references student (id),
	constraint fk__assessment__teacher__id foreign key (teacher_id) references teacher (id),
	constraint fk__assessment__subject__id foreign key (subject_id) references subject (id)
);